name = "youtoarticle"
main = "src/backend/index.ts"
compatibility_date = "2025-05-25"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSION_KV"
id = "a9f21b2b062f4965aaf98a5991fff2c9"
preview_id = "a9f21b2b062f4965aaf98a5991fff2c9"

[assets]
directory = "public/"

[observability]
enabled = true

[placement]
mode = "smart"
